# question 1

In [1]:
import numpy as np

In [2]:
from numpy import random

In [4]:
arr = np.random.randint(50,size = (5,4))
print(arr)

[[ 7  1 10 26]
 [ 5 49 26 36]
 [37 16 33 18]
 [25  2 33 18]
 [18 32 45 37]]


In [15]:
n = len(arr[0])
m = len(arr)
ad = []
for i in range(min(m, n)):
    ad.append(arr[i][n-i-1])

print(ad)

[26, 26, 16, 25]


In [17]:
for i in range(len(arr)):
    t = max(arr[i])
    print(t)

26
49
37
33
45


In [19]:
arr_mean = np.mean(arr)
print(arr_mean)

23.7


In [20]:
new_arr = arr[arr > arr_mean]
print(new_arr)

[26 49 26 36 37 33 25 33 32 45 37]


In [28]:
def numpy_boudary_traversal(matrix):
    mylist = []
    top  = 0;
    left = 0;
    right = matrix.shape[1]-1
    bottom = matrix.shape[0]-1
    for i in range(left,right+1):
        mylist.append(matrix[top][i])   
        
        
    for i in range(top+1,bottom+1):
        mylist.append(matrix[i][right])    
        
        
    for i in range(right-1,left-1,-1):
        mylist.append(matrix[bottom][i])
        
        
    for i in range(bottom-1,top-1,-1):
        mylist.append(matrix[i][left])
        
    return mylist

In [29]:
numpy_boudary_traversal(arr)

[7, 1, 10, 26, 36, 18, 18, 37, 45, 32, 18, 25, 37, 5, 7]

# question 2

In [33]:
arrr = np.random.uniform(10, size = (20))
print(arrr)

[8.59411958 7.51595313 3.39711911 3.63718044 4.06360377 6.66906093
 7.69927935 3.71166501 9.69101227 3.53384204 8.67051195 6.27381462
 8.51984123 7.45875311 1.30518195 6.12595145 7.98326757 4.77644692
 9.379058   6.97474937]


In [34]:
roundarr = np.round(arrr,2)
print(roundarr)

[8.59 7.52 3.4  3.64 4.06 6.67 7.7  3.71 9.69 3.53 8.67 6.27 8.52 7.46
 1.31 6.13 7.98 4.78 9.38 6.97]


In [36]:
mini = min(roundarr)
print(mini)

1.31


In [37]:
maxi = max(roundarr)
print(maxi)

9.69


In [39]:
medi = np.median(roundarr)
print(medi)

6.82


In [49]:
for i in range(len(roundarr)):
    if(roundarr[i] < 5):
        roundarr[i] = roundarr[i]*roundarr[i]
    i += 1
print(roundarr)

[ 8.59    7.52   11.56   13.2496 16.4836  6.67    7.7    13.7641  9.69
 12.4609  8.67    6.27    8.52    7.46    1.7161  6.13    7.98   22.8484
  9.38    6.97  ]


In [54]:
def numpy_alternate_sort(array):
    new = []
    array = sorted(array)
    
    while len(array) > 1:
        mini = array.pop(0)
        maxi = array.pop(-1)
        new += [mini, maxi]
    if array:
        new.append(array[0])
    print(new)

In [58]:
numpy_alternate_sort(new_arr)

[25, 49, 26, 45, 26, 37, 32, 37, 33, 36, 33]


# question 3

In [59]:
import pandas as pd

In [62]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ivan', 'Julia'],
    'Subject':['Math', 'English', 'Science', 'History', 'Math', 'English', 'Science', 'History', 'Math', 'English'],
    'Score': np.random.randint(50, 100, size = (10)),
    'Grades': ''
}
df = pd.DataFrame(data)

def grades(Score):
    if Score >= 90:
        return 'A'
    elif Score >= 80:
        return 'B'
    elif Score >= 70:
        return 'C'
    elif Score >= 60:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Score'].apply(grades)

In [63]:
print(df)

      Name  Subject  Score Grades Grade
0    Alice     Math     82            B
1      Bob  English     69            D
2  Charlie  Science     90            A
3    David  History     97            A
4      Eva     Math     85            B
5    Frank  English     50            F
6    Grace  Science     92            A
7   Hannah  History     86            B
8     Ivan     Math     77            C
9    Julia  English     77            C


In [64]:
df_sorted = df.sort_values(by = "Score", ascending = False)
print(df_sorted)

      Name  Subject  Score Grades Grade
3    David  History     97            A
6    Grace  Science     92            A
2  Charlie  Science     90            A
7   Hannah  History     86            B
4      Eva     Math     85            B
0    Alice     Math     82            B
8     Ivan     Math     77            C
9    Julia  English     77            C
1      Bob  English     69            D
5    Frank  English     50            F


In [66]:
avg = df.groupby('Subject')['Score'].mean()
print(avg)

Subject
English    65.333333
History    91.500000
Math       81.333333
Science    91.000000
Name: Score, dtype: float64


In [67]:
def  pandas_filter_pass(dataframe):
    return df[df['Grade'].isin(['A', 'B'])]

In [68]:
pandas_filter_pass(df)

Name  Subject  Score Grades Grade
0    Alice     Math     82            B
2  Charlie  Science     90            A
3    David  History     97            A
4      Eva     Math     85            B
6    Grace  Science     92            A
7   Hannah  History     86            B

# problem 4

In [115]:

positive = [
    "Absolutely fantastic movie! I loved every minute of it.",
    "A must-see film, incredibly well-made and captivating.",
    "This movie is a masterpiece, the acting was phenomenal.",
    "I was blown away by the visuals and the storyline.",
    "One of the best movies I've seen in years, highly recommend it.",
    "A truly enjoyable experience from start to finish.",
    "The perfect blend of humor, action, and heart.",
    "I can't say enough good things about this film.",
    "The actors were brilliant, the plot was engaging.",
    "A delightful movie that left me with a big smile.",
    "This film exceeded all my expectations, a true gem.",
    "A captivating story with unforgettable characters.",
    "The soundtrack alone makes this movie worth watching.",
    "I was on the edge of my seat the entire time, amazing.",
    "A beautiful film that will stay with me for a long time.",
    "This is a cinematic triumph, a real work of art.",
    "The direction was superb, the pacing was perfect.",
    "I was completely immersed in the world of this movie.",
    "A heartwarming story that will touch your soul.",
    "This film is a pure delight, I can't wait to watch it again.",
    "The special effects were top-notch, truly impressive.",
    "A movie that will make you laugh and cry, simply wonderful.",
    "The dialogue was sharp, the performances were outstanding.",
    "I was thoroughly entertained from beginning to end.",
    "A movie that deserves all the praise it's getting.",
    "This film is a testament to the power of storytelling.",
    "The cinematography was breathtaking, a visual feast.",
    "A movie that will stay with you long after it ends.",
    "This is a classic in the making, absolutely superb.",
    "The chemistry between the actors was palpable, fantastic.",
    "A film that will uplift your spirits and make you happy.",
    "The plot twists were unexpected, kept me guessing.",
    "A movie that is both thought-provoking and entertaining.",
    "I couldn't ask for a better movie-watching experience.",
    "This is a must-see for any movie lover, a true classic.",
    "The acting was so realistic, I felt like I was there.",
    "A movie that will make you laugh, cry, and everything in between.",
    "The characters were so well-developed, I cared about them deeply.",
    "This is a masterpiece of filmmaking, a true work of art.",
    "A movie that will stay with you for a long time, unforgettable.",
    "The production design was stunning, a visual masterpiece.",
    "I was captivated by the story, couldn't look away.",
    "A movie that is both entertaining and meaningful.",
    "The music was perfect, enhanced the emotional impact.",
    "This is a movie that I will recommend to everyone I know.",
    "The film is a perfect blend of action, drama, and comedy.",
    "The acting was top-notch, the story was captivating.",
    "A movie that is both visually stunning and emotionally resonant.",
    "I was completely engrossed in the story, a fantastic experience.",
    "This is a movie that will leave you feeling inspired and uplifted."
]
negative = [
    "Absolutely terrible movie, I hated every minute of it.",
    "A waste of time, poorly made and boring.",
    "This movie is a disaster, the acting was atrocious.",
    "I was disappointed by the visuals and the storyline.",
    "One of the worst movies I've seen in years, don't recommend it.",
    "A truly unenjoyable experience from start to finish.",
    "The worst blend of humor, action, and heart.",
    "I can't say enough bad things about this film.",
    "The actors were terrible, the plot was nonsensical.",
    "A dreadful movie that left me with a frown.",
    "This film failed all my expectations, a true disappointment.",
    "A boring story with forgettable characters.",
    "The soundtrack alone makes this movie unwatchable.",
    "I was bored the entire time, awful.",
    "A terrible film that will leave you feeling empty.",
    "This is a cinematic failure, a real mess.",
    "The direction was terrible, the pacing was awful.",
    "I was completely disengaged from the world of this movie.",
    "A heartless story that will leave you cold.",
    "This film is a pure disaster, I can't wait to forget it.",
    "The special effects were terrible, truly unimpressive.",
    "A movie that will make you cringe and yawn, simply awful.",
    "The dialogue was clunky, the performances were terrible.",
    "I was thoroughly bored from beginning to end.",
    "A movie that deserves all the criticism it's getting.",
    "This film is a testament to the failure of storytelling.",
    "The cinematography was dreadful, a visual mess.",
    "A movie that will leave you feeling empty and sad.",
    "This is a disaster in the making, absolutely terrible.",
    "The chemistry between the actors was non-existent, awful.",
    "A film that will depress your spirits and make you unhappy.",
    "The plot twists were predictable, kept me yawning.",
    "A movie that is both pointless and boring.",
    "I couldn't ask for a worse movie-watching experience.",
    "This is a must-avoid for any movie lover, a true disaster.",
    "The acting was so unrealistic, I felt like I was watching a bad play.",
    "A movie that will make you groan, sigh, and everything in between.",
    "The characters were so poorly developed, I hated them all.",
    "This is a failure of filmmaking, a true mess.",
    "A movie that will stay with you for a long time, unfortunately.",
    "The production design was awful, a visual nightmare.",
    "I was bored by the story, couldn't wait for it to end.",
    "A movie that is both unentertaining and meaningless.",
    "The music was terrible, detracted from the impact.",
    "This is a movie that I will recommend no one should see.",
    "The film is a terrible blend of action, drama, and comedy.",
    "The acting was terrible, the story was boring.",
    "A movie that is both visually unappealing and emotionally dull.",
    "I was completely disengaged from the story, a terrible experience.",
    "This is a movie that will leave you feeling disappointed and miserable."
]
Reviews = positive + negative

df = pd.DataFrame({'Review': Reviews, 'Sentiment': ['positive'] * 50 + ['negative'] * 50})
print(df)

                                               Review Sentiment
0   Absolutely fantastic movie! I loved every minu...  positive
1   A must-see film, incredibly well-made and capt...  positive
2   This movie is a masterpiece, the acting was ph...  positive
3   I was blown away by the visuals and the storyl...  positive
4   One of the best movies I've seen in years, hig...  positive
..                                                ...       ...
95  The film is a terrible blend of action, drama,...  negative
96     The acting was terrible, the story was boring.  negative
97  A movie that is both visually unappealing and ...  negative
98  I was completely disengaged from the story, a ...  negative
99  This is a movie that will leave you feeling di...  negative

[100 rows x 2 columns]


In [116]:
from sklearn.feature_extraction.text import CountVectorizer

In [117]:
vect = CountVectorizer(max_features=500, stop_words='english')
X = vect.fit_transform(df['Review'])
y = df['Sentiment']

In [118]:
from sklearn.model_selection import train_test_split

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42 )

In [120]:
from sklearn.naive_bayes import MultinomialNB

In [121]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [122]:
from sklearn.metrics import accuracy_score

In [123]:
predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

Accuracy: 0.25


In [124]:
def predict_review_sentiment(model, vect, review):
    reviewvector = vect.transform([review])
    return model.predict(reviewvector)[0]

In [125]:
print(predict_review_sentiment(model, vect, "The movie was absolutely amazing"))
print(predict_review_sentiment(model, vect, "I didn't like the film at all"))

positive
negative
